import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { part1, part2 } from "./index";

const INPUT = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

describe("Day 8", () => {
  it("Part 1", () => {
    assert.strictEqual(part1(INPUT), 14);
  });
  it("Part 2", () => {
    assert.strictEqual(part2(INPUT), 34);
  });
});
